POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Staacy Shulhlhki",
    "number": "12345678669"
}

###
POST https://phonebook-3jbv.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Nastia",
    "number": "30000099"
}